#include "infrared.h"

void Infrared_Init(void)
{
    /* Pin mux, digital-input mode and pull-ups are generated by SysConfig. */
}

uint8_t Infrared_Read(void)
{
    uint8_t value = 0U;

    /* The supplied sensor driver defines low level as black-line detection. */
    if (DL_GPIO_readPins(IR1_PORT, IR1_PIN) == 0U) {
        value |= 0x01U;
    }
    if (DL_GPIO_readPins(IR2_PORT, IR2_PIN) == 0U) {
        value |= 0x02U;
    }
    if (DL_GPIO_readPins(IR3_PORT, IR3_PIN) == 0U) {
        value |= 0x04U;
    }
    if (DL_GPIO_readPins(IR4_PORT, IR4_PIN) == 0U) {
        value |= 0x08U;
    }
    return value;
}
